### ISSUE TITLE
Directory organization for plugin managers

### ISSUE THREAD

**Issue by mnacamura** [arnoudbuzing/wolfram-vim#1]
Thank you for providing this nice syntax plugin!
For using plugin managers to install this plugin, it would be good to put the syntax file in `syntax` directory (move `wl.vim` to `syntax/wl.vim`).

**Comment by arnoudbuzing** [comment]
ok, I moved it to the `syntax` folder ... thanks for the suggestion

**Comment by mnacamura** [comment]
Thanks!
