### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by voldikss** [arnoudbuzing/wolfram-vim#2]
Hi @arnoudbuzing , thank you for implementation!
I just wrote a Vim plugin with wolfram language support and it also supplies auto completion with [deoplete](https://github.com/Shougo/deoplete.nvim).
The original syntax file of wolfram language is [here](https://github.com/neovim/neovim/blob/master/runtime/syntax/mma.vim), but it is overdue. So I would like to include your syntax file in my plugin and it will be very cool.

**Comment by arnoudbuzing** [comment]
That sounds fine to me!
